#  ___ _            _ _    _ _    __
# / __(_)_ __  _ __| (_)__(_) |_ /_/
# \__ \ | '  \| '_ \ | / _| |  _/ -_)
# |___/_|_|_|_| .__/_|_\__|_|\__\___|
#             |_| Module: ISOCurrencies 4.0
components:
  schemas:
    ActionResult:
      type: object
      properties:
        result:
          description: Action result
          type: string
    TreeviewData:
      type: object
      properties:
        item:
          description: Object item with lists of linked objects' items
          type: object
    PublicationResult:
      type: object
      properties:
        mime:
          description: MIME type
          type: string
        content:
          description: Content (plain text or base64 encoded)
          type: string
    ArrayOfISOCurrency:
      type: array
      items:
        $ref: '#/components/schemas/ISOCurrency'
    ISOCurrency:
      type: object
      properties:
        isoCurName:
          description: Name
          type: string
        isoCurCode:
          description: Code
          type: string
        row_id:
          description: ID
          type: string
        isoCurNum:
          description: Number
          type: integer
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
    bearerAuth:
      bearerFormat: Simplicite token
      scheme: bearer
      type: http
servers:
- url: https://dev40.dev.simplicite.io/api
openapi: 3.0.2
paths:
  /rest/ISOCurrency/{row_id}:
    post:
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ISOCurrency'
      description: Create business object record
      operationId: obj-isocurrency-create
      responses:
        '200':
          description: Created business object record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ISOCurrency'
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: string
        in: path
        name: row_id
        description: row ID (or _ for all row IDs)
        required: true
      tags:
      - ISOCurrency
    get:
      security:
      - bearerAuth: []
      description: Get business object record
      operationId: obj-isocurrency-get
      responses:
        '200':
          description: Business object record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ISOCurrency'
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: string
        in: path
        name: row_id
        description: row ID (or _ for all row IDs)
        required: true
      - schema:
          type: boolean
        in: query
        name: _inline_documents
        description: Inline documents?
        required: false
      - schema:
          type: boolean
        in: query
        name: _inline_thumbnails
        description: Inline documents' thumbnails?
        required: false
      - schema:
          type: boolean
        in: query
        name: _inline_objects
        description: Inline objects?
        required: false
      tags:
      - ISOCurrency
    delete:
      security:
      - bearerAuth: []
      description: Delete business object record
      operationId: obj-isocurrency-delete
      responses:
        '200':
          description: Business object deletion confirmation
          content:
            application/json: {}
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: string
        in: path
        name: row_id
        description: row ID (or _ for all row IDs)
        required: true
      tags:
      - ISOCurrency
    put:
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ISOCurrency'
      description: Update business object record
      operationId: obj-isocurrency-update
      responses:
        '200':
          description: Updated business object record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ISOCurrency'
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: string
        in: path
        name: row_id
        description: row ID (or _ for all row IDs)
        required: true
      tags:
      - ISOCurrency
  /login:
    get:
      security:
      - basicAuth: []
      description: Login
      operationId: login
      responses:
        '200':
          description: User token
          content:
            application/json: {}
            text/plain: {}
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: string
          enum:
          - json
          - oauth2
        in: query
        name: _output
        description: Optional output format
        required: false
      tags:
      - Application
  /rest/ISOCurrency:
    get:
      security:
      - bearerAuth: []
      description: Get business object metadata or search records
      operationId: obj-isocurrency-search
      responses:
        '200':
          description: Business object metadata or records of search result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfISOCurrency'
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: boolean
        in: query
        name: _metadata
        description: Metadata?
        required: false
      - schema:
          type: boolean
        in: query
        name: _count
        description: Count?
        required: false
      - schema:
          type: boolean
        in: query
        name: _doc
        description: Documentation?
        required: false
      - schema:
          type: string
        in: query
        name: isoCurName
        description: Search filter for Name
        required: false
      - schema:
          type: string
        in: query
        name: isoCurCode
        description: Search filter for Code
        required: false
      - schema:
          type: integer
        in: query
        name: isoCurNum
        description: Search filter for Number
        required: false
      tags:
      - ISOCurrency
  /logout:
    get:
      security:
      - bearerAuth: []
      description: Logout
      operationId: logout
      responses:
        '200':
          description: Logout confirmation
          content:
            application/json: {}
        '401':
          description: Authentication error
          content:
            application/json: {}
      tags:
      - Application
  /rest:
    get:
      security:
      - bearerAuth: []
      description: Application session information
      operationId: info
      responses:
        '200':
          description: Application information
          content:
            application/json: {}
        '401':
          description: Authentication error
          content:
            application/json: {}
      parameters:
      - schema:
          type: boolean
        in: query
        name: texts
        description: Texts?
        required: false
      tags:
      - Application
info:
  license:
    name: Simplicite license
    url: http://www.simplicitesoftware.com
  contact:
    name: Simplicite Software
    url: http://www.simplicitesoftware.com
    email: contact@simplicitesoftware.com
  description: REST APIs for ISOCurrencies
  title: ISOCurrencies
  version: '4.0'
